config/routes.rb
Rails.application.routes.draw do
  resources :domains

  resources :contacts

end

app/models/contact.rb
class Contact < ActiveRecord::Base
	has_and_belongs_to_many :domains
end

app/models/domain.rb
class Domain < ActiveRecord::Base
	has_and_belongs_to_many :contacts
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/contacts_controller.rb
class ContactsController < ApplicationController
  before_action :set_contact, only: [:show, :edit, :update, :destroy]

  # GET /contacts
  # GET /contacts.json
  def index
    @contacts = Contact.all
  end

  # GET /contacts/1
  # GET /contacts/1.json
  def show
    @contact = Contact.find(params[:id])
  end

  # GET /contacts/new
  def new
    @contact = Contact.new
  end

  # GET /contacts/1/edit
  def edit
    @contact = Contact.find(params[:id])
  end

  # POST /contacts
  # POST /contacts.json
  def create
    @contact = Contact.new(contact_params)

    respond_to do |format|
      if @contact.save
        format.html { redirect_to @contact, notice: 'Contact was successfully created.' }
        format.json { render :show, status: :created, location: @contact }
      else
        format.html { render :new }
        format.json { render json: @contact.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /contacts/1
  # PATCH/PUT /contacts/1.json
  def update
    @contact = Contact.find(params[:id])

    respond_to do |format|  
      if @contact.update(contact_params)
      # if @contact.update_attributes(contact_params)
        format.html { redirect_to @contact, notice: 'Contact was successfully updated.' }
        format.json { render :show, status: :ok, location: @contact }
      else
        format.html { render :edit }
        format.json { render json: @contact.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /contacts/1
  # DELETE /contacts/1.json
  def destroy
    @contact.destroy
    respond_to do |format|
      format.html { redirect_to contacts_url, notice: 'Contact was successfully destroyed.' }
      format.json { head :no_content }
      # redirect_to(:action => 'index')
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_contact
     @contact = Contact.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def contact_params
      # params[:contact] = Contact.find(params[:id])
      params.require(:contact).permit(:name, :org, :street, :city, :state, :zip, 
        :email)
      # params.permit(:name, :org, :street, :city, :state, :zip, :email)
      # params[:contact]
    end
end

app/controllers/domains_controller.rb
class DomainsController < ApplicationController
  before_action :set_domain, only: [:show, :edit, :update, :destroy]

  # GET /domains
  # GET /domains.json
  def index
    @domains = Domain.all
  end

  # GET /domains/1
  # GET /domains/1.json
  def show
  end

  # GET /domains/new
  def new
    @domain = Domain.new
  end

  # GET /domains/1/edit
  def edit
  end

  # POST /domains
  # POST /domains.json
  def create
    @domain = Domain.new(domain_params)

    respond_to do |format|
      if @domain.save
        format.html { redirect_to @domain, notice: 'Domain was successfully created.' }
        format.json { render :show, status: :created, location: @domain }
      else
        format.html { render :new }
        format.json { render json: @domain.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /domains/1
  # PATCH/PUT /domains/1.json
  def update
    respond_to do |format|
      if @domain.update(domain_params)
        format.html { redirect_to @domain, notice: 'Domain was successfully updated.' }
        format.json { render :show, status: :ok, location: @domain }
      else
        format.html { render :edit }
        format.json { render json: @domain.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /domains/1
  # DELETE /domains/1.json
  def destroy
    @domain.destroy
    respond_to do |format|
      format.html { redirect_to domains_url, notice: 'Domain was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_domain
      @domain = Domain.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def domain_params
      # params[:domain]
      params.require(:domain).permit(:iana_id, :expire_date, :domain_name)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/contacts_helper.rb
module ContactsHelper
end

app/helpers/domains_helper.rb
module DomainsHelper
end

app/views/contacts/_form.html.erb
<%= form_for @contact do |f| %>
  <% if @contact.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize @contact.errors.count, "error" %> prohibited this contact from being saved:</h2>

      <ul>
      <% @contact.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

    <div class="form-group">
      <%= f.label :name %>
      <%= f.text_field :name, class: "form-control" %>
    </div>
    <div class="form-group">
      org
      <%= f.text_field :org, class: "form-control" %>
    </div>
    <div class="form-group">
      street
      <%= f.text_field :street, class: "form-control" %>
    </div>
    <div class="form-group">
      city
      <%= f.text_field :city, class: "form-control" %>
    </div>
    <div class="form-group">
      state
      <%= f.text_field :state, class: "form-control" %>
    </div>
    <div class="form-group">
      zip
      <%= f.text_field :zip, class: "form-control" %>
    </div>
    <div class="form-group">
      email
      <%= f.text_field :email, class: "form-control" %>
    </div>

  <div class="actions">
    <%= f.submit class: "btn btn-default" %>
  </div>
<% end %>

app/views/contacts/edit.html.erb
<h1>Edit a Contact</h1>

<%= render 'form' %>

app/views/contacts/index.html.erb
<div class="container">

  <h1>Listing contacts</h1>

  <table class="table">
    <thead>
      <tr>
        <th>Name</th>
        <th>Org</th>
        <th>Street</th>
        <th>City</th>
        <th>State</th>
        <th>Zip</th>
        <th>Email</th>
        <th></th>
      </tr>
    </thead>

    <tbody>
      <% @contacts.each do |contact| %>
        <tr>
          <td><%= contact.name %></td>
          <td><%= contact.org %></td>
          <td><%= contact.street %></td>
          <td><%= contact.city %></td>
          <td><%= contact.state %></td>
          <td><%= contact.zip %></td>
          <td><%= contact.email %></td>
          <td>
            <%= link_to 'Show', contact %>
            <%= link_to 'Edit', edit_contact_path(contact) %>
            <%= link_to 'Destroy', contact, method: :delete, data: { confirm: 'Are you sure?' } %>
          </td>
        </tr>
      <% end %>
    </tbody>
  </table>

  <br>

  <%= link_to 'New Contact', new_contact_path, class: "btn btn-default" %>

</div>

app/views/contacts/new.html.erb
<h1>New contact</h1>

<%= render 'form' %>

app/views/contacts/show.html.erb
<p id="notice"><%= notice %></p>



<div class="contacts show">
  <h2>Show Contact</h2>

  <table summary="Contact detail view">
    <tr>
      <th>Name</th>
      <td><%= @contact.name %></td>
    </tr>
    <tr>
      <th>Org</th>
      <td><%= @contact.org %></td>
    </tr>
    <tr>
      <th>Street</th>
      <td><%= @contact.street %></td>
    </tr>
    <tr>
      <th>City</th>
      <td><%= @contact.city %></td>
    </tr>
    <tr>
      <th>State</th>
      <td><%= @contact.state %></td>
    </tr>
    <tr>
      <th>Zip</th>
      <td><%= @contact.zip %></td>
    </tr>
    <tr>
      <th>Email</th>
      <td><%= @contact.email %></td>
    </tr>
    <tr>
      <th>Updated</th>
      <td><%= @contact.updated_at %></td>
    </tr>
  </table>

</div>

app/views/domains/_form.html.erb
<%= form_for @domain do |f| %>
  <% if @domain.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@domain.errors.count, "error") %> prohibited this domain from being saved:</h2>

      <ul>
      <% @domain.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

    t.datetime "created_at"
    t.datetime "updated_at"
    t.integer  "iana_id"
    t.string   "expire_date"
    t.string   "domain_name"

    <div class="form-group">
      iana_id
      <%= f.text_field :iana_id, class: "form-control" %>
    </div>
    <div class="form-group">
      expire_date
      <%= f.text_field :expire_date, class: "form-control" %>
    </div>
    <div class="form-group">
      domain_name
      <%= f.text_field :domain_name, class: "form-control" %>
    </div>

  <div class="actions">
    <%= f.submit class: "btn btn-default" %>
  </div>
<% end %>

app/views/domains/edit.html.erb
<h1>Editing domain</h1>

<%= render 'form' %>

<%= link_to 'Show', @domain %> |
<%= link_to 'Back', domains_path %>

app/views/domains/index.html.erb
<div class="container">

  <h1>Listing domains</h1>

  <table class="table">
    <thead>
      <tr>
        <th>IANA ID</th>
        <th>Expire Date</th>
        <th>Domain Name</th>
        <th>Created At</th>
        <th>Updated At</th>
        <th></th>
      </tr>
    </thead>

    <tbody>
      <% @domains.each do |domain| %>
        <tr>
          <td><%= domain.iana_id %></td>
          <td><%= domain.expire_date %></td>
          <td><%= domain.domain_name %></td>
          <td><%= domain.created_at %></td>
          <td><%= domain.updated_at %></td>
          <td>
            <%= link_to 'Show', domain %>
            <%= link_to 'Edit', edit_domain_path(domain) %>
            <%= link_to 'Destroy', domain, method: :delete, data: { confirm: 'Are you sure?' } %>
          </td>
        </tr>
      <% end %>
    </tbody>
  </table>

  <br>

  <%= link_to 'New Domain', new_domain_path, class: "btn btn-default" %>

</div>

app/views/domains/new.html.erb
<h1>New domain</h1>

<%= render 'form' %>

<%= link_to 'Back', domains_path %>

app/views/domains/show.html.erb
<p id="notice"><%= notice %></p>

<%= link_to 'Edit', edit_domain_path(@domain) %> |
<%= link_to 'Back', domains_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Dr2</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<div class="container">
  <%= yield %>
</div>

</body>
</html>